development:
 adapter: postgresql
 host: localhost
 database: dota
 username: postgres
 password: postgres
 encoding: unicode


test:
 adapter: postgresql
 host: localhost
 database: dota_test
 username: postgres
 password: postgres
 encoding: unicode

production:
 adapter: postgresql
 host: localhost
 database: dota_draft_production
 username: postgres
 password: postgres
 encoding: unicode



